#!/usr/bin/env bash

# Function to check if Discord is installed for the given flavor
is_product_installed() {
    local product="$1"
    local flavor="$2"
    if [[ "$product" == "discord" ]]; then
        if [[ -e "/usr/bin/Discord$flavor" && -e "/usr/share/applications/discord$flavor.desktop" && -e "/usr/share/icons/discord$flavor.png" ]]; then
            return 0
        else
            return 1
        fi
    elif [[ "$product" == "betterdiscord" ]]; then
        dcmod="$HOME/.config/discord"
        case "$flavor" in
            "")
                dcmod+="/"
                ;;
            "Canary")
                dcmod+="canary/"
                ;;
            "PTB")
                dcmod+="ptb/"
                ;;
        esac

        x_y_z_directory=$(find "$dcmod" -maxdepth 1 -type d -regex '.*/[0-9]+\.[0-9]+\.[0-9]+$' | sort -r | head -n 1)

        dcmod="$x_y_z_directory/modules"
        index_file="$dcmod/discord_desktop_core/index.js"
        betterdiscord_line='require("'$HOME'/.config/BetterDiscord/data/betterdiscord.asar");'

        if [[ -e "$index_file" ]]; then
            if grep -Fxq "$betterdiscord_line" "$index_file"; then
                return 0
            else
                return 1
            fi
        else
            return 1
        fi
    else
        return 1
    fi
}

detect_package_manager() {
  if command -v apt &>/dev/null; then
    echo "Your package manager is apt"
  elif command -v dnf &>/dev/null; then
    echo "Your package manager is dnf"
  elif command -v pacman &>/dev/null; then
    echo "Your package manager is pacman"
  elif command -v zypper &>/dev/null; then
    echo "Your package manager is zypper"
  elif command -v apk &>/dev/null; then
    echo "Your package manager is apk"
  elif command -v emerge &>/dev/null; then
    echo "Your package manager is emerge"
  else
    echo "Could not detect your package manager"
  fi
}

# Function to install Discord based on the flavor
install_product() {
    local product="$1"
    local flavor="$2"

    # BetterDiscord stays the same
    bdurl="https://github.com/BetterDiscord/BetterDiscord/releases/latest/download/betterdiscord.asar"

    # Determine the appropriate URL based on the flavor
    case "$flavor" in
        "")
            dcurl="https://discordapp.com/api/download?platform=linux&format=tar.gz"
            ;;
        "Canary")
            dcurl="https://discordapp.com/api/download/canary?platform=linux&format=tar.gz"
            ;;
        "PTB")
            dcurl="https://discordapp.com/api/download/ptb?platform=linux&format=tar.gz"
            ;;
        *)
            echo "Invalid flavor $flavor. Run list flavors to get a list of available flavors."
            return 1
            ;;
    esac

    case "$product" in
        "discord")
            # Download and install Discord
            cd ~/
            mkdir -p ~/.local/bin
            wget "$dcurl" -O discord.tar.gz
            tar -xvf discord.tar.gz -C ~/.local/bin
            sudo ln -s ~/.local/bin/Discord$flavor/discord.png /usr/share/icons/discord$flavor.png
            sudo ln -s ~/.local/bin/Discord$flavor/Discord$flavor /usr/bin

                # Generate the desktop file based on the flavor
            mkdir -p ~/.local/share/applications/
            cat > ~/.local/share/applications/discord$flavor.desktop <<EOL
[Desktop Entry]
Name=Discord $flavor
Exec=/usr/bin/Discord$flavor
Icon=/usr/share/icons/discord$flavor.png
Terminal=false
Type=Application
Categories=Network;InstantMessaging;
EOL

            sudo ln -sf ~/.local/share/applications/discord$flavor.desktop /usr/share/applications/discord$flavor.desktop

            echo "Discord$flavor installed successfully!"
            ;;
        "betterdiscord")
            dcmod="$HOME/.config/discord"
            case "$flavor" in
            "")
                dcmod+="/"
                ;;
            "Canary")
                dcmod+="canary/"
                ;;
            "PTB")
                dcmod+="ptb/"
                ;;
            esac

            x_y_z_directory=$(find "$dcmod" -maxdepth 1 -type d -regex '.*/[0-9]+\.[0-9]+\.[0-9]+$' | sort -r | head -n 1)

            dcmod="$x_y_z_directory/modules"

            wget "$bdurl" -O betterdiscord.asar

            mkdir -p "$HOME/.config/BetterDiscord/data/"
            
            mv betterdiscord.asar "$HOME/.config/BetterDiscord/data/"

            asar_name="$HOME/.config/BetterDiscord/data/betterdiscord.asar"

            printf $'require("%s");\nmodule.exports = require(\'./core.asar\');\n' "${asar_name/\\/\\\\}" > "$dcmod/discord_desktop_core/index.js"

            echo "BetterDiscord for Discord$flavor installed successfully!"
            ;;
        *)
            echo "Cannot install $product. Unknown product."
            ;;
    esac

}

# Function to remove Discord based on the flavor
remove_product() {
    local product="$1"
    local flavor="$2"

    case "$product" in
        "discord")
            if is_product_installed "$product" "$flavor"; then
                # Remove symbolic links and current installation of Discord
                sudo rm /usr/bin/Discord$flavor
                sudo rm -rf ~/.local/bin/Discord$flavor
                sudo rm /usr/share/applications/discord$flavor.desktop

                # Remove the icon
                sudo rm /usr/share/icons/discord$flavor.png

                echo "Discord$flavor removed successfully!"
            else
                echo "Discord$flavor is not installed."
            fi
            ;;
        "betterdiscord")
            if is_product_installed "$product" "$flavor"; then
                dcmod="$HOME/.config/discord"
                case "$flavor" in
                    "")
                        dcmod+="/"
                        ;;
                    "Canary")
                        dcmod+="canary/"
                        ;;
                    "PTB")
                        dcmod+="ptb/"
                        ;;
                esac

                x_y_z_directory=$(find "$dcmod" -maxdepth 1 -type d -regex '.*/[0-9]+\.[0-9]+\.[0-9]+$' | sort -r | head -n 1)

                dcmod="$x_y_z_directory/modules"
                index_file="$dcmod/discord_desktop_core/index.js"

                echo "module.exports = require('./core.asar');" > $index_file
            else
                echo "BetterDiscord for Discord$flavor is not installed."
            fi
            ;;
        *)
            echo "Cannot remove $product. Unknown product."
            ;;
    esac
}

# Function to update Discord based on the flavor
update_product() {
    local product="$1"
    local flavor="$2"

    case "$product" in
        "discord")
            if is_product_installed "$product" "$flavor"; then
                # Remove symbolic links
                sudo rm /usr/bin/Discord$flavor
                sudo rm /usr/share/applications/discord$flavor.desktop

                # Remove the icon
                sudo rm /usr/share/icons/discord$flavor.png

                # Overwrite existing installation
                install_product "$product" "$flavor"
            else
                echo "An active installation of Discord$flavor was not detected. Skipping update."
            fi
            ;;
        "betterdiscord")
            if is_product_installed "$product" "$flavor"; then
                install_product "$product" "$flavor"
            else
                echo "An active installation of BetterDiscord for Discord$flavor was not detected. Skipping update."
            fi
            ;;
        *)
            echo "Cannot update $product. Unknown product."
            ;;
    esac
}


display_help() {
    echo "Manager for Discord and BetterDiscord"
    echo "Usage: discord-manager command product flavor"
    echo "Available commands: help, list, install, remove, update"
    echo "Available products: Discord, BetterDiscord"
    echo "Available lists: dependencies, flavors"
    echo "To perform update of all active installations of all products made with this script, run update full"
}

# Main script logic
command="$1"
product="$2"
flavor="$3"

case "$command" in
    "help")
        display_help
        ;;
    "install")
        install_product "$product" "$flavor"
        ;;
    "remove")
        remove_product "$product" "$flavor"
        ;;
    "update")
        if [[ "$product" == "full" ]]; then
            update_product "discord" ""
            update_product "discord" "Canary"
            update_product "discord" "PTB"
            update_product "betterdiscord" ""
            update_product "betterdiscord" "Canary"
            update_product "betterdiscord" "PTB"
        else
            update_product "$product" "$flavor"
        fi
        ;;
    "list")
        case "$product" in
            "dependencies")
                echo "Ubuntu package names: libc6 libasound2 libatomic1 libgconf-2-4 libnotify4 libnspr4 libnss3 libstdc++6 libxss1 libxtst6 libappindicator1"
                echo "Find and install the correct packages using your distribution's package manager"
                echo "Trying to detect package manager"
                detect_package_manager
                ;;
            "flavors")
                echo "Canary, PTB, blank for stable. Case sensitive."
                ;;
            *)
                echo "Cannot display a list for $product. Unknown product."
                ;;
        esac
        ;;
    *)
        echo "Unknown command $command"
        echo "Use the help command to display the help message."
        ;;
esac
